' Gambas module file

' Modulo de inicio de la aplicación Gestor de Álbumes Compartidos en Linux Avanzado

' Constantes de la aplicación
Private Const DIRECTORIO_GACELA As String = ".config/gacela"
Private Const BIBLIOTECA_COMPARTIDA As String = "/usr/share/gacela/biblioteca"
Private Const GRUPO_GACELA As String = "gacela-users"

' Clases para inyección de dependencias (patrón DI manual)
Private $configuration As Configuration
Private $log4Gambas As Log4Gambas3
Private $connDB As SQLiteContext
Private $photorepository As PhotoRepository
' Private $servicioArchivos As FileService
' Private $biblioteca As Library

Public Sub Main()

  Dim response As Integer
  Dim formMain As FMain

  $configuration = New Configuration
  $log4Gambas = $configuration.InitializeLogger()

  If $configuration.IsFirstRun Then
    ' lanzamos ventana de advertencia para que seleccione como desea iniciar la aplicación
    response = Message.Warning(("Hemos detectado que la primera vez que ejecuta la aplicación. Debe seleccionar cual de es la configuración con la que desea iniciar. Siempre la puede cambiar en el apartado de configuraciones"), ("Biblioteca privada"), ("Multiusuario"), ("Cancelar"))

    Select Case response
      Case $configuration.LibraryType_Private
        $log4Gambas.Debug("Seleccion de biblioteca privada")
        ' Le indicamos a la clase configuration que cargue ambiente privado
        $configuration.InitializePrivateSettings()

      Case $configuration.LibraryType_Shared
        $log4Gambas.Debug("Seleccion de biblioteca multiusuario")
        ' Le indicamos a la clase configuration que cargue ambiente multiusuario
        $configuration.InitializeMultiUserSettings()

      Case Else
        Stop
    End Select

  Else
    ' Cargamos el ambiente configurado
    $configuration.InitializeEnvironment()
  Endif

  $log4Gambas.Info("Iniciando Gacela v" & Application.Version)

  $connDB = New SQLiteContext($configuration, $log4gambas)
  $photorepository = New PhotoRepository($log4Gambas, $connDB, $configuration)

  formMain = New FMain($log4gambas, $photorepository)
  formMain.Show()

Catch
  Print "Se detecto un problema grave y se detendra la aplicación" & Error.Text

End
